version: '2'
services:
  db:
    image: postgres:9.4
  web:
    build:
      context: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      RAILS_PORT: 3000
      DB_HOST: db
      DB_USERNAME: postgres
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
