version: '2'
services:
  db:
    image: postgres:9.4
  web:
    build:
      context: .
    command: rails s
    environment:
      RAILS_PORT: 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
