# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d961e1a5f62149ee1a13ce07d8a8839077613eaca3535ac90eeb2976aa74ef48d179239354ba1c64134db8663f4b65375b6a8ef16485459c1046b7a4daf2719

test:
  secret_key_base: d090b4515dc3bbfdfa7e9abc584a0cd5b250489f71225cc51560014f3bdb76962588a02c5c2b9ccd875c339cc5e722cff8ba763656db8c83bc899d58dee53c95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
